[package]
name = "findlargedir"
version = "0.4.0"
authors = ["Dinko Korunic <dinko.korunic@gmail.com>"]
categories = ["command-line-utilities"]
description = "find all blackhole directories with a huge amount of filesystem entries in a flat structure"
repository = "https://github.com/dkorunic/findlargedir"
readme = "README.md"
license = "MIT"
exclude = [".gitignore"]
edition = "2021"

[dependencies]
jwalk = "0.8.1"
rayon = "1.6.1"
num_cpus = "1.15.0"
tempfile = "3.3.0"
anyhow = "1.0.68"
human_format = "1.0.3"
human_bytes = { version = "0.4.1", features = ["fast"] }
humantime = "2.1.0"
clap = { version = "4.1.4", features = ["derive"] }
ctrlc = { version = "3.2.4", features = ["termination"] }
rm_rf = "0.6.2"
ansi_term = "0.12.1"
fs-err = "2.9.0"
indicatif = { version = "0.17.3", features = ["rayon"] }
cfg-if = "1.0"

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
tikv-jemallocator = "0.5"

[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))'.dependencies]
tikv-jemallocator = "0.5"

[profile.release]
lto = true
strip = true
