[package]
name = "findlargedir"
version = "0.3.3"
authors = ["Dinko Korunic <dinko.korunic@gmail.com>"]
categories = ["command-line-utilities"]
description = "find all blackhole directories with a huge amount of filesystem entries in a flat structure"
repository = "https://github.com/dkorunic/findlargedir"
readme = "README.md"
license = "MIT"
exclude = [".gitignore"]
edition = "2021"

[dependencies]
jwalk = "~0"
rayon = "~1"
num_cpus = "~1"
tempfile = "~3"
anyhow = "~1"
human_format = "~1"
human_bytes = { version = "~0", features = ["fast"] }
humantime = "~2"
clap = { version = "~4", features = ["derive"] }
ctrlc = { version = "~3", features = ["termination"] }
rm_rf = "~0"
ansi_term = "~0"
fs-err = "~2"
indicatif = { version = "~0", features = ["rayon"] }

[profile.release]
lto = true
strip = true
